name: marchant
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  fuzzy: ^0.5.1
  file_picker: ^8.0.0+1
  firebase_core: ^2.27.0
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  http: ^1.2.0
  shared_preferences: ^2.2.3
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/

